apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web
spec:
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  destination:
    namespace: web-app
    name: minikube
  project: default
  source:
    path: apps/web/overlays/stagging
    repoURL: git@github.com:thisiscaetano/kubernetes-global-manifest.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true